//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tekoding.KoIdentity.Abstraction.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tekoding.KoIdentity.Abstraction.Resources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ObjectNullFailure {
            get {
                return ResourceManager.GetString("ObjectNullFailure", resourceCulture);
            }
        }
        
        internal static string DatabaseCreationFailure {
            get {
                return ResourceManager.GetString("DatabaseCreationFailure", resourceCulture);
            }
        }
        
        internal static string DatabaseDeletionFailure {
            get {
                return ResourceManager.GetString("DatabaseDeletionFailure", resourceCulture);
            }
        }
        
        internal static string ObjectInvalidFailure {
            get {
                return ResourceManager.GetString("ObjectInvalidFailure", resourceCulture);
            }
        }
        
        internal static string DatabaseSelectionFailure {
            get {
                return ResourceManager.GetString("DatabaseSelectionFailure", resourceCulture);
            }
        }
        
        internal static string ObjectStateUnmodifiedFailure {
            get {
                return ResourceManager.GetString("ObjectStateUnmodifiedFailure", resourceCulture);
            }
        }
        
        internal static string DatabaseUpdateFailure {
            get {
                return ResourceManager.GetString("DatabaseUpdateFailure", resourceCulture);
            }
        }
    }
}
