trigger:
  - main
  - develop

stages:
  - stage: SonarCloudAnalyze
    displayName: 'SonarQube Analyzing Solution'
    jobs:
      - template: sonarcloud.yml
  - stage: PublishNuGet
    displayName: 'Publish to private NuGet Feed'
    jobs:
      - template: artifacts.yml